# Generated by Django 5.2 on 2025-06-15 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Event Name")),
                ("slug", models.SlugField(help_text="URL identifier", unique=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="Location"
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(verbose_name="Event Date")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Provide a brief summary of the event, including the full event dates (e.g., May 14 - May 22, 2025), as well as the time and time zone if relevant. Maximum 255 characters.",
                        max_length=255,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("hybrid", "Hybrid"),
                            ("in_person", "On-Site"),
                            ("online", "Online"),
                        ],
                        default="in_person",
                        help_text="Specify if on-site, online or hybrid event type",
                        max_length=12,
                        verbose_name="Event Format",
                    ),
                ),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("local_community", "Local Community"),
                            ("conference", "Conference"),
                        ],
                        default="local_community",
                        help_text="Classify the event as a local community event or a conference",
                        max_length=20,
                    ),
                ),
                (
                    "community",
                    models.CharField(max_length=255, verbose_name="Community Name"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="Event Post or Website"
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
