# Generated by Django 5.2 on 2025-04-27 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Event Name")),
                ("slug", models.SlugField(help_text="URL identifier", unique=True)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="Location"
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Event Date and Time")),
                (
                    "time_zone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Time Zone"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief event summary (max 255 characters)",
                        max_length=255,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("hybrid", "Hybrid"),
                            ("in_person", "In-Person"),
                            ("online", "Online"),
                        ],
                        default="in_person",
                        help_text="Physical, online, or hybrid event type",
                        max_length=12,
                        verbose_name="Event Format",
                    ),
                ),
                (
                    "community",
                    models.CharField(max_length=255, verbose_name="Community Name"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="Event Website"
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
