services:
  app:
    build:
      context: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    env_file: .env
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/

  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
